export const MODULE_ID          = 'users';
export const API_SUB_URL        = '/users';

export const PROFILE_FORM_NAME        = 'USER_PROFILE_FORM';
export const PROFILE_FORM_NAME_SUBMIT = PROFILE_FORM_NAME + '_SUBMIT';
export const PROFILE_FORM_NAME_SUCCESS = PROFILE_FORM_NAME + '_SUCCESS';
export const PROFILE_FORM_NAME_FAILURE = PROFILE_FORM_NAME + '_FAILURE';

export const PROFILE_PASSWORD_FORM_NAME         = 'USER_PR_PASSWORD_FORM';
export const PROFILE_PASSWORD_FORM_NAME_SUBMIT  = PROFILE_PASSWORD_FORM_NAME + '_SUBMIT';
export const PROFILE_PASSWORD_FORM_NAME_SUCCESS = PROFILE_PASSWORD_FORM_NAME + '_SUCCESS';
export const PROFILE_PASSWORD_FORM_NAME_FAILURE = PROFILE_PASSWORD_FORM_NAME + '_FAILURE';


export const DEALER_INFO_FORM_NAME        = 'DEALER_INFO_FORM';
export const DEALER_INFO_FORM_NAME_SUBMIT = DEALER_INFO_FORM_NAME + '_SUBMIT';
export const DEALER_INFO_FORM_NAME_SUCCESS = DEALER_INFO_FORM_NAME + '_SUCCESS';
export const DEALER_INFO_FORM_NAME_FAILURE = DEALER_INFO_FORM_NAME + '_FAILURE';