export const MODULE_ID          = 'contructions';
export const API_SUB_URL        = '/contructions';

export const API_SUB_URL_USERS  = 'users';
export const API_SUB_URL_CONTRUCTION_NOTES = 'contruction-notes';

export const API_SUB_URL_CONTRUCTION_DATA_ENTRY   = '/contruction-data-entries';
export const API_SUB_URL_CONTRUCTION_PLANNER = '/contruction-planners';

export const SCHEMA_CONTRUCTIONS          = 'contructions';
export const SCHEMA_CONTRUCTION_NOTES     = 'notes';
export const SCHEMA_CONTRUCTION_DATA_ENTRIES = 'contructionDataEntries';
export const SCHEMA_CONTRUCTION_DATA_ENTRY_STAFFS    = 'staffs';

export const DOCS_TYPE_CONTRUCTIONS_SHEET   = 'contructions-sheet';

export {PAGINATION_ITEMS_PER_PAGE} from '../../constants';

export const CONTRUCTION_LIST_FILTER_FORM_NAME          = 'CONTRUCTION_LIST_FILTER_FORM';
export const CONTRUCTION_LIST_FILTER_FORM_NAME_SUBMIT   = CONTRUCTION_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const CONTRUCTION_LIST_FILTER_FORM_NAME_SUCCESS  = CONTRUCTION_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const CONTRUCTION_LIST_FILTER_FORM_NAME_FAILURE  = CONTRUCTION_LIST_FILTER_FORM_NAME + '_FAILURE';

export const CONTRUCTION_DETAIL_FORM_NAME             = 'CONTRUCTION_DETAIL_FORM';
export const CONTRUCTION_DETAIL_FORM_NAME_SUBMIT      = CONTRUCTION_DETAIL_FORM_NAME + '_SUBMIT';
export const CONTRUCTION_DETAIL_FORM_NAME_SUCCESS     = CONTRUCTION_DETAIL_FORM_NAME + '_SUCCESS';
export const CONTRUCTION_DETAIL_FORM_NAME_FAILURE     = CONTRUCTION_DETAIL_FORM_NAME + '_FAILURE';

export const SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME           = 'SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME';
export const SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME_SUBMIT    = SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME + '_SUBMIT';
export const SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME_SUCCESS   = SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME + '_SUCCESS';
export const SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME_FAILURE   = SHARED_CONTRUCTION_ESTIMATED_CONTRUCTION_DATE_FORM_NAME + '_FAILURE';

export const CONTRUCTION_NOTE_DETAIL_FORM_NAME             = 'CONTRUCTION_NOTE_DETAIL_FORM';
export const CONTRUCTION_NOTE_DETAIL_FORM_NAME_SUBMIT      = CONTRUCTION_NOTE_DETAIL_FORM_NAME + '_SUBMIT';
export const CONTRUCTION_NOTE_DETAIL_FORM_NAME_SUCCESS     = CONTRUCTION_NOTE_DETAIL_FORM_NAME + '_SUCCESS';
export const CONTRUCTION_NOTE_DETAIL_FORM_NAME_FAILURE     = CONTRUCTION_NOTE_DETAIL_FORM_NAME + '_FAILURE';

export const SHARED_CONTRUCTION_EDIT_FORM_NAME          = 'SHARED_CONTRUCTION_EDIT_FORM';
export const SHARED_CONTRUCTION_EDIT_FORM_NAME_SUBMIT   = SHARED_CONTRUCTION_EDIT_FORM_NAME + '_SUBMIT';
export const SHARED_CONTRUCTION_EDIT_FORM_NAME_SUCCESS  = SHARED_CONTRUCTION_EDIT_FORM_NAME + '_SUCCESS';
export const SHARED_CONTRUCTION_EDIT_FORM_NAME_FAILURE  = SHARED_CONTRUCTION_EDIT_FORM_NAME + '_FAILURE';

export const SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME          = 'SHARED_CONTRUCTION_LIST_FILTER_FORM';
export const SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME_SUBMIT   = SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME_SUCCESS  = SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME_FAILURE  = SHARED_CONTRUCTION_LIST_FILTER_FORM_NAME + '_FAILURE';

export const CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME          = 'CONTRUCTION_DATA_ENTRY_ADD_FORM';
export const CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME_SUBMIT   = CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME + '_SUBMIT';
export const CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME_SUCCESS  = CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME + '_SUCCESS';
export const CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME_FAILURE  = CONTRUCTION_DATA_ENTRY_DETAIL_FORM_NAME + '_FAILURE';

export const CONTRUCTION_DATA_ENTRY_ADD_STAFF_FORM_NAME      = 'CONTRUCTION_DATA_ENTRY_ADD_STAFF_FORM_NAME';

export const CONTRUCTION_FIELDS_WITH_JOB_TRACKING = {
    CONCRETE: 'Concrete',
    STEEL_FIXER: 'Steel_Fixer'
}

export const PREDIFINED_CONTRUCTION_FIELDS = [
    {name: 'Concrete', value: 'Concrete'}, 
    {name: 'Steel Fixer', value: 'Steel_Fixer'}, 
    {name: 'Plumbing', value: 'Plumbing'}, 
    {name: 'Electrical', value: 'Electrical'}, 
    {name: 'Office', value: 'Office'}, 
    {name: 'Other', value: 'Other'}
];

export const INSURANCE_POLICY_TYPES = [
    {id: 'Text', name: 'Text'}, 
    {id: 'File', name: 'File'}
];