export const API_SUB_URL        = '/authentication';
export const API_SUB_AUTHENTICATION_JWT_URL        = '/authenticationJWT';

export const LOGIN_FORM_NAME        = 'AUTH_LOGIN_FORM';
export const LOGIN_FORM_NAME_SUBMIT = LOGIN_FORM_NAME + '_SUBMIT';
export const LOGIN_FORM_NAME_SUCCESS = LOGIN_FORM_NAME + '_SUCCESS';
export const LOGIN_FORM_NAME_FAILURE = LOGIN_FORM_NAME + '_FAILURE';

export const FORGOT_PASSWORD_FORM_NAME        = 'AUTH_FORGOT_FORM';
export const FORGOT_PASSWORD_FORM_NAME_SUBMIT = FORGOT_PASSWORD_FORM_NAME + '_SUBMIT';
export const FORGOT_PASSWORD_FORM_NAME_SUCCESS = FORGOT_PASSWORD_FORM_NAME + '_SUCCESS';
export const FORGOT_PASSWORD_FORM_NAME_FAILURE = FORGOT_PASSWORD_FORM_NAME + '_FAILURE';

export const PASSWORD_RESET_FORM_NAME           = 'AUTH_PW_RESET_FORM';
export const PASSWORD_RESET_FORM_NAME_SUBMIT    = PASSWORD_RESET_FORM_NAME + '_SUBMIT';
export const PASSWORD_RESET_FORM_NAME_SUCCESS   = PASSWORD_RESET_FORM_NAME + '_SUCCESS';
export const PASSWORD_RESET_FORM_NAME_FAILURE   = PASSWORD_RESET_FORM_NAME + '_FAILURE';