export const MODULE_ID          = 'clients';
export const API_SUB_URL        = '/clients';

export const SCHEMA_CLIENTS     = 'clients';

export {PAGINATION_ITEMS_PER_PAGE} from '../../constants';


export const CLIENTS_LIST_FILTER_FORM_NAME          = 'CLIENTS_LIST_FILTER_FORM';
export const CLIENTS_LIST_FILTER_FORM_NAME_SUBMIT   = CLIENTS_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const CLIENTS_LIST_FILTER_FORM_NAME_SUCCESS  = CLIENTS_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const CLIENTS_LIST_FILTER_FORM_NAME_FAILURE  = CLIENTS_LIST_FILTER_FORM_NAME + '_FAILURE';

export const CLIENTS_ADD_FORM_NAME          = 'CLIENTS_ADD_FORM';
export const CLIENTS_ADD_FORM_NAME_SUBMIT   = CLIENTS_ADD_FORM_NAME + '_SUBMIT';
export const CLIENTS_ADD_FORM_NAME_SUCCESS  = CLIENTS_ADD_FORM_NAME + '_SUCCESS';
export const CLIENTS_ADD_FORM_NAME_FAILURE  = CLIENTS_ADD_FORM_NAME + '_FAILURE';

export const CLIENTS_EDIT_FORM_NAME          = 'CLIENTS_EDIT_FORM';
export const CLIENTS_EDIT_FORM_NAME_SUBMIT   = CLIENTS_EDIT_FORM_NAME + '_SUBMIT';
export const CLIENTS_EDIT_FORM_NAME_SUCCESS  = CLIENTS_EDIT_FORM_NAME + '_SUCCESS';
export const CLIENTS_EDIT_FORM_NAME_FAILURE  = CLIENTS_EDIT_FORM_NAME + '_FAILURE';
